### ISSUE TITLE
身边暂时没有 windows 想问一下：这种壳装网页的程序用新版 net 如果打包成 exe 会有多大？

### ISSUE THREAD

**Issue by shenlebantongying** [congzhangzh/desktoploveblazorweb#1]

**Comment by congzhangzh** [comment]
我打包完有79MB差不多，完全独立，内置.NET。

如果打包成使用系统.NET运行时的话，会小非常多吧，我明天试下。

另外，打包选项很多，对大小应该都有影响。

**Comment by congzhangzh** [comment]
四种场景：

1. 不带.Net, 不带Ready To Run， 2M
2. 不带.Net, 带Ready To Run，    3M
3. 带.Net， 不启用裁剪， 79M
4. 带.Net， 启用裁剪，    47M

47M，非常酷了

**Comment by congzhangzh** [comment]
虽然是SingleFile模式，但是还是有些网站文件在外面，感觉可以用资源整合的方式，也整合进入Exe文件里面去。

**Comment by congzhangzh** [comment]
虽然是SingleFile模式，但是还是有些网站文件路在外面，感觉可以用资源整合的方式，也整合进入Exe文件里面去。

**Comment by shenlebantongying** [comment]
哈哈哈, 以前47mb已经是算是 bloatware 了。坐等那天 windows 预装 net。

**Comment by congzhangzh** [comment]
@shenlebantongying 现在的电脑，40M算小的了。关键是能快开发，快迭代，快交付就好了
