### ISSUE TITLE
System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'

### ISSUE THREAD

**Issue by gismofx** [congzhangzh/desktoploveblazorweb#2]
@congzhangzh Thanks for putting this together. I forked your repo and tried to run the project, no changes, and I get an error when running the project, I think from webviewsharp. It throws the error here:

`using var webview = new Webview();` in Program.cs on line 57. 

> StackTrace	"   at SharpWebview.Bindings.webview_create(Int32 debug, IntPtr window)\r\n   at SharpWebview.Webview..ctor(Boolean debug, Boolean interceptExternalLinks)\r\n   at BlazorBrowserNativeStyle.Program.OpenInLine(String address)

**Comment by congzhangzh** [comment]
Maybe you need install webview2 run time, As this webview depend on it?

**Comment by congzhangzh** [comment]
@gismofx  maybe your can try the work in progress branch which focus on wpf&webview2,  https://github.com/congzhangzh/desktoploveblazorweb/tree/wpf_wip

**Comment by gismofx** [comment]
@congzhangzh I tried wpf_wip branch. I think I got it to work, but maybe not as intended.... I started IIS Express and two windows opened. One completely blank and another my Chrome tab with the application. This works, but with an extra window.

If I run BlazorBrowserNativeStyle, I get just one blank window. No UI. When I publish and run the exe, I get the same result as running BlasorBrowserNativeStyle. A completely blank window.

**Comment by gismofx** [comment]
@congzhangzh both branches work after installing webview2 runtime! Thank you! Does this work on MacOS?

**Comment by congzhangzh** [comment]
@gismofx 
first, the wpf version support fixed version webview2, you can put webview2 fixed version directly in WebView2 directory alongside with you app, it will be very usefull when you deploy you application in the future, as edge chromium & webview2 runtime is somelevel of new stuff！

>> Does this work on MacOS?
Not now, but should work in the future by three possible way:
1. use webview way, this should works across all the branch, but it does not work on my Mac book now, I do not know why!
2. use webview2 way, I fell Microsoft will make WebView2 support Windows/Linux/Mac in the future
3. use webview way, https://github.com/SteveSandersonMS/WebWindow/tree/master/src/WebWindow.Native

I think WebView2 wil be the best solution in the future, but  if you need cross platform support now, you may need split out of WebWindow.Native, and just use it, as Microsoft soft is really fat and slow!

For the future of WebWindow, you can see https://github.com/SteveSandersonMS/WebWindow/issues/86
