### ISSUE TITLE
MacOS UI Empty/No Display

### ISSUE THREAD

**Issue by gismofx** [congzhangzh/desktoploveblazorweb#4]
I just want to document/capture this in a separate issue. 

If webview_sharp is cross platform, why does this example not work on MacOS? 

Have you successfully tried the webview_sharp examples on MacOS?
[Webview Sharp examples](https://github.com/webview/webview_csharp/tree/master/examples)

**Comment by congzhangzh** [comment]
Maybe the native depend part need recompile as Mac OS X keep updating.

BTW, if the upstream stop trace the native part, I prefer some more light way, which is easy to manager, like webwindow's implement, which point in https://github.com/SteveSandersonMS/WebWindow/issues/127 

The best result is that microsoft will release WebView2 cross platform, I think there is no barrierfor webview2 team, and they will do that in a near future, you can follow https://github.com/MicrosoftEdge/WebView2Feedback/issues/645

>Have you successfully tried the webview_sharp examples on MacOS?
>Webview Sharp examples

I can give a try laterly.

**Comment by gismofx** [comment]
@congzhangzh It will be great if/when WebView2 is cross platform...

Maybe it does need to be compiled on MacOS for it to work, but here are the precompiled libs, maybe these will work for MacOS when compiling from windows. 

https://github.com/webview/webview_csharp/tree/master/libs

**Comment by congzhangzh** [comment]
@gismofx I test on my mbp, it works

**Comment by gismofx** [comment]
> @gismofx I test on my mbp, it works

That's good. Was it compiled on Windows and transferred to mbp or compiled on mbp?

**Comment by congzhangzh** [comment]
It seems it just works, I just use **dotnet run**

**Comment by gismofx** [comment]
> It seems it just works, I just use **dotnet run**
> […](#)

From the MBP?

**Comment by congzhangzh** [comment]
yes

**Comment by gismofx** [comment]
Does your Blazor example run too?

**Comment by gismofx** [comment]
@congzhangzh I compiled and tried to run from a mac( Using VS for Mac), but I get no window or display. Is there something I need to do to get it to work on mac?

**Comment by congzhangzh** [comment]
@gismofx seems works now, you can have a try, I do some adjust according to https://github.com/webview/webview_csharp

```C#
using(var webview = new Webview())
{
    webview
        .SetTitle("The Hitchhicker")             
        .SetSize(1024, 768, WebviewHint.None)
        .SetSize(800, 600, WebviewHint.Min)
        .Navigate(new UrlContent("https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy_(novel)"))
        .Run();
}

**Comment by gismofx** [comment]
@congzhangzh This worked on mac! Thank you! I was also successful in publishing and launching as well via dotnet command in terminal.
