### ISSUE TITLE
Access Inspector on MacOS?

### ISSUE THREAD

**Issue by gismofx** [congzhangzh/desktoploveblazorweb#5]
Hey, I submitted an issue here https://github.com/webview/webview/issues/529 and wondering if you have the same trouble with accessing the webview/webkit inspector on MacOS. 

My project is using MudBlazor for UI and It's doing some funny things when rendering. No issue on Windows, only Mac.

**Comment by congzhangzh** [comment]
For blazor library,  you can give https://github.com/ant-design-blazor/ant-design-blazor a try, very promising

**Comment by gismofx** [comment]
@congzhangzh I should have closed this sooner. I had some missing images and cause some rendering issues. All my rendering issues mostly went away now that I have inspector working on MacOS.

**Comment by congzhangzh** [comment]
Ok, thanks for your information!
